/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author PROF-REC-TEC
 */
public class VistaMenuGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaMenuGUI.class.getName());

    /**
     * Creates new form Menu
     */
    public VistaMenuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jmb_principal = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jmi_salir = new javax.swing.JMenuItem();
        jm_gestion = new javax.swing.JMenu();
        jmi_profesor = new javax.swing.JMenuItem();
        jmi_equipoComputo = new javax.swing.JMenuItem();
        jmi_reservas = new javax.swing.JMenuItem();
        jmi_estudiantes = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmi_acercaDe = new javax.swing.JMenuItem();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Sistema de Gestión de Reservas");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Reservas");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Sistema de Gestión de Reservas");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Bienvenido");

        jm_archivo.setText("Archivo");

        jmi_salir.setText("Salir");
        jm_archivo.add(jmi_salir);

        jmb_principal.add(jm_archivo);

        jm_gestion.setText("Gestión");

        jmi_profesor.setText("Profesores");
        jm_gestion.add(jmi_profesor);

        jmi_equipoComputo.setText("Equipos de Computo");
        jm_gestion.add(jmi_equipoComputo);

        jmi_reservas.setText("Reservas");
        jm_gestion.add(jmi_reservas);

        jmi_estudiantes.setText("Estudiantes");
        jm_gestion.add(jmi_estudiantes);

        jmb_principal.add(jm_gestion);

        jMenu1.setText("Help");

        jmi_acercaDe.setText("Acerca de");
        jMenu1.add(jmi_acercaDe);

        jmb_principal.add(jMenu1);

        setJMenuBar(jmb_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel3)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaMenuGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jm_archivo;
    public javax.swing.JMenu jm_gestion;
    public javax.swing.JMenuBar jmb_principal;
    public javax.swing.JMenuItem jmi_acercaDe;
    public javax.swing.JMenuItem jmi_equipoComputo;
    public javax.swing.JMenuItem jmi_estudiantes;
    public javax.swing.JMenuItem jmi_profesor;
    public javax.swing.JMenuItem jmi_reservas;
    public javax.swing.JMenuItem jmi_salir;
    // End of variables declaration//GEN-END:variables
}
